// Logros: una razón simple para volver a jugar. Cada uno se revisa contra el
// progreso guardado (sin necesidad de rastrear eventos en tiempo real) y se
// puede reclamar una sola vez por perfil.

import { getBestScore } from "./storage.js";

export const ACHIEVEMENTS = [
  {
    id: "primeros_pasos",
    name: "Primeros pasos",
    icon: "👣",
    reward: 10,
    desc: "Juega tu primera partida de cualquier juego.",
    isDone: (p) => Object.keys(p.bestScores).length > 0,
  },
  {
    id: "recolector",
    name: "Recolector Novato",
    icon: "🍬",
    reward: 20,
    desc: "Consigue 100 puntos en Recolecta y Corre.",
    isDone: (p) => getBestScore(p, "recolecta") >= 100,
  },
  {
    id: "tetris_master",
    name: "Maestro del Tetris",
    icon: "🧱",
    reward: 20,
    desc: "Consigue 500 puntos en Tetris de Productos.",
    isDone: (p) => getBestScore(p, "tetris") >= 500,
  },
  {
    id: "campeon",
    name: "Campeón Matichoc",
    icon: "🏆",
    reward: 40,
    desc: "Completa las 6 canchas de Recolecta y Corre.",
    isDone: (p) => (p.unlockedLevel || 0) >= 6,
  },
  {
    id: "ahorrista",
    name: "Ahorrista de Cacao",
    icon: "💰",
    reward: 30,
    desc: "Gana 200 monedas Chocolate Dubai en total.",
    isDone: (p) => (p.stats.totalCoinsEarned || 0) >= 200,
  },
  {
    id: "encestador",
    name: "Encestador Estrella",
    icon: "🏀",
    reward: 20,
    desc: "Consigue 100 puntos en Lanzamientos de Básquet.",
    isDone: (p) => getBestScore(p, "basquet_tiros") >= 100,
  },
  {
    id: "cazador",
    name: "Cazador de Malvaviscos",
    icon: "🎯",
    reward: 25,
    desc: "Consigue 1500 puntos en Choco Blaster 3D.",
    isDone: (p) => getBestScore(p, "fps3d") >= 1500,
  },
  {
    id: "escalador",
    name: "Escalador de Cacao",
    icon: "🦘",
    reward: 20,
    desc: "Consigue 1500 puntos en Salto Choco 3D.",
    isDone: (p) => getBestScore(p, "salto") >= 1500,
  },
  {
    id: "piloto",
    name: "Piloto Choco",
    icon: "🏎️",
    reward: 20,
    desc: "Consigue 1500 puntos en Autos de Chocolate 3D.",
    isDone: (p) => getBestScore(p, "autos") >= 1500,
  },
  {
    id: "memorion",
    name: "Memorión Matichoc",
    icon: "🧠",
    reward: 25,
    desc: "Consigue 3000 puntos en Memoria Matichoc 3D.",
    isDone: (p) => getBestScore(p, "memoria") >= 3000,
  },
  {
    id: "chocolatero",
    name: "Chocolatero",
    icon: "🍫",
    reward: 15,
    desc: "Guarda tu primera creación en Crea tu Chocolate.",
    isDone: (p) => (p.creations || []).length >= 1,
  },
  {
    id: "obra_maestra",
    name: "Obra Maestra",
    icon: "🎨",
    reward: 30,
    desc: "Consigue 450 puntos de creatividad en Crea tu Chocolate.",
    isDone: (p) => getBestScore(p, "creador") >= 450,
  },
  {
    id: "parkourista",
    name: "Parkourista Matichoc",
    icon: "🧗",
    reward: 30,
    desc: "Llega a la meta del Parkour Choco 3D.",
    isDone: (p) => (p.stats.parkourFinishes || 0) >= 1,
  },
  {
    id: "equilibrista",
    name: "Equilibrista Matichoc",
    icon: "🤸",
    reward: 20,
    desc: "Consigue 80 puntos en Saltos de Porristas.",
    isDone: (p) => getBestScore(p, "porristas") >= 80,
  },
];
